#!/bin/bash

# prereqs: helm init (tiller should be running in the kube-system namespace)

helm repo add riffrepo https://riff-charts.storage.googleapis.com
helm repo update
helm install --name demo --set httpGateway.service.type=NodePort riffrepo/riff
